name: CI pipeline

on: [ push, pull_request ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt-get install imagemagick lftp
      - name: Compress images
        run: |
          find ./img/veranstaltungen -name '*.jpg' -exec mogrify -resize 1920x1920 -quality 30\> {} \;
          find ./img/vorstandschaft -name '*.jpg' -exec mogrify -resize 1920x1920 -quality 40\> {} \;
          find ./img/startseite -name '*.jpg' -exec mogrify -resize 1920x1920 -quality 35\> {} \;
      - name: Remove unnecessary files
        run: rm -r .github .git
      - name: Pull .well-known
        continue-on-error: true
        run: lftp -u ${{ secrets.FTP_USER }},${{ secrets.FTP_PASSWORD }} -e "set ssl:verify-certificate no; mirror .well-known ./; quit;" ${{ secrets.FTP_URL }}
      - name: Remove old bundle
        continue-on-error: true
        run: lftp -u ${{ secrets.FTP_USER }},${{ secrets.FTP_PASSWORD }} -e "set ssl:verify-certificate no; rm -r .; quit;" ${{ secrets.FTP_URL }}
      - name: Push new bundle
        run: lftp -u ${{ secrets.FTP_USER }},${{ secrets.FTP_PASSWORD }} -e "set ssl:verify-certificate no; mirror -R . .; quit;" ${{ secrets.FTP_URL }}